import random

randcount = 0  # keeps track of values already used
N = 0  # number of random values generated by the user
n = 0  # values inside the circle

N = int(input("Kuinka monta pistettä haluat luoda?"))
while randcount < N:
    x = random.uniform(-1, 1)
    y = random.uniform(-1, 1)
    randcount += 1
    if x ** 2 + y ** 2 < 1:
        n += 1
pi = (4 * n) / N
print(f"Pii on likiarvoltaan {pi}")
